import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P, Quantico } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pressStart2P = Press_Start_2P({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-press-start-2p',
});

const quantico = Quantico({
  weight: ['400', '700'],  // Available weights for Quantico
  subsets: ['latin'],
  variable: '--font-quantico',
});

export const metadata: Metadata = {
  title: "Stavalley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pressStart2P.variable} ${quantico.variable} antialiased ${pressStart2P.className}`}
      >
        {children}
      </body>
    </html>
  );
}
